### ISSUE TITLE
Cannot install with npm

### ISSUE THREAD

**Issue by vedantroy** [tdolsen/getenv.ts#11]
It says I must use pnpm to install.
Probably b/c of this: https://pnpm.io/only-allow-pnpm

**Comment by tdolsen** [comment]
Didn't think anyone was using this package, so haven't given this issue any attention. I'll get on it!

You can version lock it to `1.2.0` until a fix is published.

**Comment by tdolsen** [comment]
This issue has now been fixed in version `1.4.0`.

**Comment by vedantroy** [comment]
Thanks!
